# Generated by Django 4.1.7 on 2023-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[(1, "免费版"), (2, "收费版"), (3, "其他")],
                        default=1,
                        verbose_name="收费类型",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="标题")),
                ("price", models.PositiveIntegerField(verbose_name="价格")),
                ("project_num", models.PositiveIntegerField(verbose_name="项目数")),
                (
                    "project_member",
                    models.PositiveIntegerField(help_text="G", verbose_name="项目成员数"),
                ),
                (
                    "project_space",
                    models.PositiveIntegerField(help_text="M", verbose_name="单个项目空间"),
                ),
                ("per_file_size", models.PositiveIntegerField(verbose_name="单文件大小")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(db_index=True, max_length=32, verbose_name="用户名"),
        ),
    ]
