# Generated by Django 4.1.7 on 2023-02-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_pricepolicy_alter_userinfo_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "待支付"), (2, "已支付")], verbose_name="订单状态"
                    ),
                ),
                (
                    "actual_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="实际支付价格"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="订单开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="订单结束时间"),
                ),
                ("count", models.IntegerField(verbose_name="购买数量(年)")),
                (
                    "order",
                    models.CharField(max_length=64, unique=True, verbose_name="订单号"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="订单创建时间"),
                ),
                (
                    "price_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.pricepolicy",
                        verbose_name="价格策略",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
