# Generated by Django 4.1.7 on 2023-02-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricepolicy",
            name="project_member",
            field=models.PositiveIntegerField(help_text="M", verbose_name="项目成员数"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="count",
            field=models.IntegerField(help_text="0表示无限期", verbose_name="购买数量(年)"),
        ),
    ]
