# Generated by Django 4.1.7 on 2023-02-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_pricepolicy_project_member_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="项目名称")),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="项目描述"
                    ),
                ),
                (
                    "color",
                    models.SmallIntegerField(
                        choices=[
                            (1, "#56b8eb"),
                            (2, "#f28033"),
                            (3, "#ebc656"),
                            (4, "#a2d148"),
                            (5, "#20BFA4"),
                            (6, "#7461c2"),
                            (7, "#20bfa3"),
                        ],
                        default=1,
                        max_length=10,
                        verbose_name="项目颜色",
                    ),
                ),
                ("star", models.BooleanField(default=False, verbose_name="标星")),
                (
                    "join_count",
                    models.SmallIntegerField(default=1, verbose_name="参与人数"),
                ),
                (
                    "use_space",
                    models.BigIntegerField(
                        default=0, help_text="字节", verbose_name="已用空间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userinfo",
                        verbose_name="创建者",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="create_date",
            new_name="create_time",
        ),
        migrations.CreateModel(
            name="ProjectPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.BooleanField(default=False, verbose_name="星标")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
