# Generated by Django 4.1.7 on 2023-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_project_rename_create_date_transaction_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=models.SmallIntegerField(
                choices=[
                    (1, "#56b8eb"),
                    (2, "#f28033"),
                    (3, "#ebc656"),
                    (4, "#a2d148"),
                    (5, "#20BFA4"),
                    (6, "#7461c2"),
                    (7, "#20bfa3"),
                ],
                default=1,
                verbose_name="项目颜色",
            ),
        ),
    ]
