# Generated by Django 4.1.7 on 2023-02-28 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_rename_projectpartner_projectuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="user",
        ),
    ]
