# Generated by Django 4.1.7 on 2023-02-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_remove_projectuser_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="project",
        ),
        migrations.AddField(
            model_name="projectuser",
            name="user",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.userinfo",
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
    ]
