# Generated by Django 4.1.7 on 2023-02-28 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_remove_projectuser_project_projectuser_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="user",
        ),
    ]
