# Generated by Django 4.1.7 on 2023-03-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_filerepository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filerepository",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="web.filerepository",
                verbose_name="父目录",
            ),
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=12, verbose_name="模块")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.project",
                        verbose_name="项目",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuesType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="类型名称")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.project",
                        verbose_name="项目",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=32, verbose_name="主题")),
                ("desc", models.TextField(verbose_name="问题描述")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "新建"),
                            (2, "处理中"),
                            (3, "已解决"),
                            (4, "已忽略"),
                            (5, "待反馈"),
                            (6, "已关闭"),
                            (7, "重新打开"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority_level",
                    models.IntegerField(
                        choices=[("info", "低"), ("warning", "中"), ("danger", "高")],
                        verbose_name="优先度",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "mode",
                    models.SmallIntegerField(
                        choices=[(1, "公开模式"), (2, "隐私模式")], default=1, verbose_name="模式"
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "latest_update_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "assign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task",
                        to="web.userinfo",
                        verbose_name="处理人",
                    ),
                ),
                (
                    "attention",
                    models.ManyToManyField(
                        blank=True,
                        related_name="observe",
                        to="web.userinfo",
                        verbose_name="关注人",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="create_problems",
                        to="web.userinfo",
                        verbose_name="创建者",
                    ),
                ),
                (
                    "issues_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.issuestype",
                        verbose_name="问题类型",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child",
                        to="web.issues",
                        verbose_name="关联问题",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.project",
                        verbose_name="项目",
                    ),
                ),
            ],
        ),
    ]
