# Generated by Django 4.1.7 on 2023-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_alter_filerepository_parent_model_issuestype_issues"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Model",
            new_name="Module",
        ),
    ]
