# Generated by Django 4.1.7 on 2023-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0020_alter_issues_end_time_alter_issues_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="priority_level",
            field=models.CharField(
                choices=[("info", "低"), ("warning", "中"), ("danger", "高")],
                default="info",
                max_length=12,
                verbose_name="优先度",
            ),
        ),
    ]
