# Generated by Django 4.1.7 on 2023-03-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0021_alter_issues_priority_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="issues",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.module",
                verbose_name="模块",
            ),
        ),
    ]
