# Generated by Django 4.1.7 on 2023-03-05 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0023_record"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="IssuesReply",
        ),
    ]
